export interface Practitioner {
  id: string;
  name: string;
  credentials: string;
  city: string;
  state: string;
  specialties: string[];
  phone: string;
  website: string;
  gabrielScore: number;
  tier: 'Ascended Guardian' | 'Luminary' | 'Torchbearer' | 'Pathfinder';
  bio: string;
  connectionStatus?: 'active' | 'pending' | 'inactive';
  lastSync?: string | null;
}

export const PRACTITIONER_SPECIALTIES = [
  'All',
  'Naturopathic Doctor',
  'Functional Medicine',
  'Acupuncture',
  'Chiropractic',
  'Integrative Medicine',
  'Hormone Health',
  'Thyroid Specialist',
  'Autoimmune Specialist',
  'Nutrition',
  'Genetics/MTHFR',
  'Neurology',
  'Women\'s Health',
] as const;

export type PractitionerSpecialty = typeof PRACTITIONER_SPECIALTIES[number];

export const MOCK_PRACTITIONERS: Practitioner[] = [
  {
    id: 'p1',
    name: 'Dr. Sarah Chen',
    credentials: 'ND',
    city: 'San Francisco',
    state: 'CA',
    specialties: ['Naturopathic Doctor', 'Functional Medicine'],
    phone: '+14155678900',
    website: 'https://www.sfnaturalmedicine.com/',
    gabrielScore: 96,
    tier: 'Ascended Guardian',
    bio: 'San Francisco-based naturopathic doctor combining functional medicine diagnostics with evidence-based natural therapies. Specializes in complex chronic conditions, hormonal health, and integrative treatment protocols rooted in clinical research.',
    connectionStatus: 'active',
    lastSync: '2h ago',
  },
  {
    id: 'p2',
    name: 'Dr. Michael Torres',
    credentials: 'ND, LAc',
    city: 'Portland',
    state: 'OR',
    specialties: ['Naturopathic Doctor', 'Acupuncture'],
    phone: '+15032244929',
    website: 'https://www.heartspringhealth.com/',
    gabrielScore: 94,
    tier: 'Luminary',
    bio: 'Dual-licensed naturopathic physician and acupuncturist practicing at Heart Spring Health in Portland. Integrates East-West healing traditions with modern diagnostics for a comprehensive approach to chronic illness, pain management, and whole-body wellness.',
    connectionStatus: 'active',
    lastSync: '5h ago',
  },
  {
    id: 'p3',
    name: 'Dr. Amy Myers',
    credentials: 'MD',
    city: 'Austin',
    state: 'TX',
    specialties: ['Functional Medicine'],
    phone: '+15123835343',
    website: 'https://www.amymyersmd.com/',
    gabrielScore: 97,
    tier: 'Ascended Guardian',
    bio: 'Renowned functional medicine physician and bestselling author specializing in autoimmune conditions, thyroid dysfunction, and gut health. Empowers patients to reverse chronic illness through physician-formulated protocols and root-cause medicine.',
    connectionStatus: 'pending',
    lastSync: null,
  },
  {
    id: 'p4',
    name: 'Dr. Mark Hyman',
    credentials: 'MD',
    city: 'Lenox',
    state: 'MA',
    specialties: ['Functional Medicine'],
    phone: '+14136379991',
    website: 'https://www.drhyman.com/',
    gabrielScore: 98,
    tier: 'Ascended Guardian',
    bio: 'Internationally recognized leader in functional medicine, bestselling author, and advocate for food-as-medicine. Focuses on metabolic health, longevity, and reversing chronic disease through nutrition, lifestyle, and advanced diagnostics.',
  },
  {
    id: 'p5',
    name: 'Dr. Josh Axe',
    credentials: 'DNM, DC',
    city: 'Nashville',
    state: 'TN',
    specialties: ['Naturopathic Doctor', 'Chiropractic'],
    phone: '+16159537544',
    website: 'https://draxe.com/',
    gabrielScore: 93,
    tier: 'Luminary',
    bio: 'Doctor of natural medicine, chiropractor, and clinical nutritionist with a passion for helping people get well using nutrition, natural remedies, and functional fitness. Bestselling author and founder of one of the largest natural health websites in the world.',
  },
  {
    id: 'p6',
    name: 'Dr. Jolene Brighten',
    credentials: 'ND',
    city: 'Portland',
    state: 'OR',
    specialties: ['Naturopathic Doctor', 'Hormone Health'],
    phone: '+15038949965',
    website: 'https://www.drbrighten.com/',
    gabrielScore: 95,
    tier: 'Luminary',
    bio: 'Naturopathic endocrinologist and leading expert in post-birth control syndrome and hormonal health. Bestselling author helping women worldwide understand and optimize their hormones through evidence-based natural medicine protocols.',
  },
  {
    id: 'p7',
    name: 'Dr. Peter Osborne',
    credentials: 'DC',
    city: 'Sugar Land',
    state: 'TX',
    specialties: ['Functional Medicine', 'Chiropractic'],
    phone: '+12812402229',
    website: 'https://www.gluten-free-society.org/',
    gabrielScore: 91,
    tier: 'Luminary',
    bio: 'Functional medicine chiropractor and recognized authority on gluten sensitivity, celiac disease, and grain-free living. Founder of the Gluten Free Society, dedicated to educating practitioners and patients on the far-reaching effects of gluten and dietary inflammation.',
  },
  {
    id: 'p8',
    name: 'Dr. Alan Christianson',
    credentials: 'NMD',
    city: 'Scottsdale',
    state: 'AZ',
    specialties: ['Naturopathic Doctor', 'Thyroid Specialist'],
    phone: '+14806570003',
    website: 'https://drchristianson.com/',
    gabrielScore: 96,
    tier: 'Ascended Guardian',
    bio: 'Naturopathic medical doctor and New York Times bestselling author specializing in thyroid and adrenal conditions. A leading voice in natural endocrinology with decades of clinical experience helping patients restore metabolic health.',
  },
  {
    id: 'p9',
    name: 'Dr. Izabella Wentz',
    credentials: 'PharmD',
    city: 'Boulder',
    state: 'CO',
    specialties: ['Functional Medicine', 'Thyroid Specialist'],
    phone: '+17204412722',
    website: 'https://thyroidpharmacist.com/',
    gabrielScore: 94,
    tier: 'Luminary',
    bio: 'Pharmacist turned thyroid specialist and #1 New York Times bestselling author. Known as the Thyroid Pharmacist, she has dedicated her career to finding the root causes of Hashimoto\'s thyroiditis and helping patients put their autoimmune condition into remission.',
  },
  {
    id: 'p10',
    name: 'Dr. Will Cole',
    credentials: 'IFMCP, DNM',
    city: 'Pittsburgh',
    state: 'PA',
    specialties: ['Functional Medicine'],
    phone: '+17249000321',
    website: 'https://drwillcole.com/',
    gabrielScore: 95,
    tier: 'Luminary',
    bio: 'Leading functional medicine practitioner specializing in uncovering the hidden causes behind chronic illness through breakthrough diagnostic testing rarely done in conventional settings. Bestselling author and pioneer of personalized telehealth functional medicine.',
  },
  {
    id: 'p11',
    name: 'Dr. Deanna Minich',
    credentials: 'PhD',
    city: 'Seattle',
    state: 'WA',
    specialties: ['Functional Medicine', 'Nutrition'],
    phone: '+12065357300',
    website: 'https://deannaminich.com/',
    gabrielScore: 92,
    tier: 'Luminary',
    bio: 'Functional medicine nutritionist and researcher with expertise in the intersection of color, food, and health. Develops whole-spectrum wellness programs integrating science-backed nutrition with mind-body practices for vibrant, energized living.',
  },
  {
    id: 'p12',
    name: 'Dr. Tom O\'Bryan',
    credentials: 'DC',
    city: 'San Diego',
    state: 'CA',
    specialties: ['Functional Medicine', 'Autoimmune Specialist'],
    phone: '+18777267220',
    website: 'https://thedr.com/',
    gabrielScore: 93,
    tier: 'Luminary',
    bio: 'World-renowned expert on gluten sensitivity, autoimmune disease, and the gut-immune connection. Internationally recognized speaker and educator helping practitioners and patients understand the mechanisms behind autoimmune activation and how to arrest them.',
  },
  {
    id: 'p13',
    name: 'Dr. Aviva Romm',
    credentials: 'MD',
    city: 'Berkshires',
    state: 'MA',
    specialties: ['Integrative Medicine', 'Women\'s Health'],
    phone: '+14135284200',
    website: 'https://avivaromm.com/',
    gabrielScore: 97,
    tier: 'Ascended Guardian',
    bio: 'Yale-trained physician, midwife, and herbalist bridging the best of traditional wisdom and modern medicine. A leading authority on women\'s and children\'s integrative health, she empowers patients with evidence-based natural approaches to hormonal and reproductive wellness.',
  },
  {
    id: 'p14',
    name: 'Dr. Lara Briden',
    credentials: 'ND',
    city: 'Christchurch',
    state: 'NZ',
    specialties: ['Naturopathic Doctor', 'Hormone Health'],
    phone: '+6433792820',
    website: 'https://www.larabriden.com/',
    gabrielScore: 92,
    tier: 'Luminary',
    bio: 'Bestselling author and naturopathic doctor known as the Period Revolutionary. Explores natural treatments for PCOS, endometriosis, heavy periods, perimenopause, and metabolic health with over 25 years of clinical experience in women\'s hormonal medicine.',
  },
  {
    id: 'p15',
    name: 'Dr. Ben Lynch',
    credentials: 'ND',
    city: 'Seattle',
    state: 'WA',
    specialties: ['Naturopathic Doctor', 'Genetics/MTHFR'],
    phone: '+14253981320',
    website: 'https://www.drbenlynch.com/',
    gabrielScore: 96,
    tier: 'Ascended Guardian',
    bio: 'Naturopathic physician and leading authority on MTHFR gene mutations, methylation, and nutrigenomics. Bestselling author of Dirty Genes, pioneering the clinical application of epigenetics in naturopathic and functional medicine practice.',
  },
  {
    id: 'p16',
    name: 'Dr. Datis Kharrazian',
    credentials: 'DHSc',
    city: 'San Diego',
    state: 'CA',
    specialties: ['Functional Medicine', 'Neurology'],
    phone: '+18582596926',
    website: 'https://drknews.com/',
    gabrielScore: 95,
    tier: 'Luminary',
    bio: 'Harvard Medical School researcher and clinical scientist specializing in functional neurology, autoimmune conditions, and complex chronic disease. Author of groundbreaking texts on thyroid and brain health used by practitioners worldwide.',
  },
  {
    id: 'p17',
    name: 'Dr. Terry Wahls',
    credentials: 'MD',
    city: 'Iowa City',
    state: 'IA',
    specialties: ['Functional Medicine', 'Autoimmune Specialist'],
    phone: '+13193564296',
    website: 'https://terrywahls.com/',
    gabrielScore: 94,
    tier: 'Luminary',
    bio: 'Clinical professor of medicine and pioneering researcher who reversed her own progressive multiple sclerosis through diet and lifestyle interventions. Creator of the Wahls Protocol, a therapeutic approach to autoimmune conditions backed by clinical trials.',
  },
  {
    id: 'p18',
    name: 'Dr. Jill Carnahan',
    credentials: 'MD',
    city: 'Louisville',
    state: 'CO',
    specialties: ['Functional Medicine'],
    phone: '+13039937910',
    website: 'https://www.jillcarnahan.com/',
    gabrielScore: 96,
    tier: 'Ascended Guardian',
    bio: 'Board-certified family medicine physician and functional medicine expert specializing in mold illness, complex chronic disease, and gut health. A cancer survivor herself, she brings deep personal understanding and clinical expertise to patients with difficult-to-diagnose conditions.',
  },
  {
    id: 'p19',
    name: 'Dr. Dan Kalish',
    credentials: 'DC',
    city: 'Del Mar',
    state: 'CA',
    specialties: ['Functional Medicine'],
    phone: '+18587244594',
    website: 'https://kalishwellness.com/',
    gabrielScore: 91,
    tier: 'Luminary',
    bio: 'Functional medicine pioneer who has trained over 1,000 practitioners in the Kalish Method. Specializes in adrenal, gut, and detoxification protocols using advanced lab-based diagnostics. Known for systematic, data-driven approaches to restoring health.',
  },
  {
    id: 'p20',
    name: 'Dr. Sachin Patel',
    credentials: 'DC',
    city: 'Atlanta',
    state: 'GA',
    specialties: ['Functional Medicine', 'Chiropractic'],
    phone: '+17705527500',
    website: 'https://www.livingproof.institute/',
    gabrielScore: 93,
    tier: 'Luminary',
    bio: 'Functional medicine chiropractor and founder of the Living Proof Institute. Focuses on empowering patients to become the proof that health transformation is possible through root-cause resolution, advanced diagnostics, and personalized lifestyle medicine.',
  },
];
