export interface ScannedSupplement {
  barcode: string;
  name: string;
  brand: string;
  dosage: string;
  ingredients: string;
  servingDirections: string;
  timeRecommendation: 'morning' | 'afternoon' | 'evening';
  withFood: boolean;
  absorptionTips: string;
  interactions: string[];
  category: string;
}

export const SUPPLEMENT_DATABASE: ScannedSupplement[] = [
  {
    barcode: '693749330017',
    name: 'Magnesium Bisglycinate',
    brand: 'Thorne',
    dosage: '200mg per capsule',
    ingredients: 'Magnesium bisglycinate chelate, hypromellose capsule, leucine',
    servingDirections: 'Take 1-2 capsules daily',
    timeRecommendation: 'evening',
    withFood: false,
    absorptionTips: 'Glycinate form is highly bioavailable. Take 1-2 hours before bed for best sleep benefits. Avoid taking with calcium supplements as they compete for absorption.',
    interactions: ['blood pressure medications', 'antibiotics', 'bisphosphonates'],
    category: 'Mineral',
  },
  {
    barcode: '733739014948',
    name: 'Vitamin D3 5000 IU',
    brand: 'NOW Foods',
    dosage: '5,000 IU per softgel',
    ingredients: 'Vitamin D3 (as cholecalciferol), extra virgin olive oil, softgel capsule',
    servingDirections: 'Take 1 softgel daily with a fat-containing meal',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'Fat-soluble vitamin — always take with a meal containing healthy fats. Pair with K2 for optimal calcium metabolism. Test levels every 3 months.',
    interactions: ['thiazide diuretics', 'steroids', 'weight loss drugs'],
    category: 'Vitamin',
  },
  {
    barcode: '737870195313',
    name: 'Super Ubiquinol CoQ10',
    brand: 'Life Extension',
    dosage: '100mg per softgel',
    ingredients: 'Ubiquinol (Kaneka), d-Limonene, rosemary extract',
    servingDirections: 'Take 1 softgel daily with food',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'Ubiquinol is the active form — 8x better absorbed than ubiquinone. Take with fatty meal. Essential if on statins, which deplete CoQ10.',
    interactions: ['blood thinners', 'insulin', 'chemotherapy drugs'],
    category: 'Antioxidant',
  },
  {
    barcode: '658010114233',
    name: 'Dr. Formulated Probiotics',
    brand: 'Garden of Life',
    dosage: '50 Billion CFU per capsule',
    ingredients: 'Lactobacillus acidophilus, Bifidobacterium lactis, prebiotic fiber',
    servingDirections: 'Take 1 capsule daily before a meal',
    timeRecommendation: 'morning',
    withFood: false,
    absorptionTips: 'Take on an empty stomach 20-30 minutes before breakfast. Stomach acid is lowest in the morning, improving survival of probiotics. Refrigerate after opening.',
    interactions: ['immunosuppressants', 'antifungals'],
    category: 'Probiotic',
  },
  {
    barcode: '768990017414',
    name: 'Ultimate Omega',
    brand: 'Nordic Naturals',
    dosage: '1,280mg Omega-3 per serving',
    ingredients: 'EPA 650mg, DHA 450mg, other omega-3s 180mg, natural lemon flavor',
    servingDirections: 'Take 2 softgels daily with food',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'Triglyceride form absorbs 70% better than ethyl ester. Take with your largest meal for best absorption. Store in cool, dark place.',
    interactions: ['blood thinners', 'blood pressure medications', 'aspirin'],
    category: 'Essential Fatty Acid',
  },
  {
    barcode: '693749050018',
    name: 'Basic B Complex',
    brand: 'Thorne',
    dosage: 'Full spectrum B vitamins',
    ingredients: 'B1 thiamine, B2 riboflavin 5-phosphate, B3 niacin, B5, B6 P-5-P, B12 methylcobalamin, folate 5-MTHF, biotin',
    servingDirections: 'Take 1 capsule daily',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'Active methylated forms for superior bioavailability. Take in the morning — B vitamins can be energizing and may disrupt sleep if taken late. May turn urine bright yellow (harmless).',
    interactions: ['levodopa', 'phenytoin', 'methotrexate'],
    category: 'Vitamin',
  },
  {
    barcode: '669076010018',
    name: 'KSM-66 Ashwagandha',
    brand: 'Jarrow Formulas',
    dosage: '300mg per capsule',
    ingredients: 'Ashwagandha root extract (KSM-66), cellulose, magnesium stearate',
    servingDirections: 'Take 1 capsule once or twice daily with meals',
    timeRecommendation: 'evening',
    withFood: true,
    absorptionTips: 'KSM-66 is the most clinically studied extract. Take with dinner — adaptogenic effects support cortisol regulation and sleep. Allow 4-6 weeks for full benefits.',
    interactions: ['thyroid medications', 'sedatives', 'immunosuppressants'],
    category: 'Adaptogen',
  },
  {
    barcode: '021078025344',
    name: 'NAC (N-Acetyl Cysteine)',
    brand: 'NOW Foods',
    dosage: '600mg per capsule',
    ingredients: 'N-Acetyl Cysteine, cellulose, stearic acid, silica',
    servingDirections: 'Take 1 capsule 1-3 times daily',
    timeRecommendation: 'morning',
    withFood: false,
    absorptionTips: 'Best absorbed on an empty stomach. Precursor to glutathione — your master antioxidant. Take with vitamin C to enhance glutathione production.',
    interactions: ['nitroglycerin', 'blood thinners', 'activated charcoal'],
    category: 'Amino Acid',
  },
  {
    barcode: '693749540014',
    name: 'Zinc Picolinate',
    brand: 'Thorne',
    dosage: '30mg per capsule',
    ingredients: 'Zinc picolinate, hypromellose capsule, leucine',
    servingDirections: 'Take 1 capsule daily',
    timeRecommendation: 'evening',
    withFood: true,
    absorptionTips: 'Picolinate form is highly bioavailable. Take with dinner — zinc on empty stomach may cause nausea. Space 2+ hours from iron and calcium supplements.',
    interactions: ['penicillamine', 'quinolone antibiotics', 'tetracycline'],
    category: 'Mineral',
  },
  {
    barcode: '033984032811',
    name: 'Curcumin Phytosome',
    brand: 'Meriva',
    dosage: '500mg per capsule',
    ingredients: 'Curcuma longa root extract complexed with phosphatidylcholine (Meriva)',
    servingDirections: 'Take 1 capsule twice daily with meals',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'Phytosome technology increases absorption 29x vs standard curcumin. Take with a meal containing black pepper or fat for even better uptake.',
    interactions: ['blood thinners', 'diabetes medications', 'gallbladder medications'],
    category: 'Anti-inflammatory',
  },
  {
    barcode: '793573254870',
    name: 'Berberine',
    brand: 'Thorne',
    dosage: '500mg per capsule',
    ingredients: 'Berberine HCl (from Indian barberry root), hypromellose capsule',
    servingDirections: 'Take 1 capsule 2-3 times daily with meals',
    timeRecommendation: 'afternoon',
    withFood: true,
    absorptionTips: 'Take with meals to reduce GI side effects. Split doses throughout the day for stable blood sugar support. Do not combine with metformin without supervision.',
    interactions: ['metformin', 'cyclosporine', 'blood pressure medications'],
    category: 'Botanical',
  },
  {
    barcode: '853146007010',
    name: 'L-Theanine',
    brand: 'Sports Research',
    dosage: '200mg per softgel',
    ingredients: 'Suntheanine L-Theanine, organic coconut oil, softgel capsule',
    servingDirections: 'Take 1 softgel daily',
    timeRecommendation: 'evening',
    withFood: false,
    absorptionTips: 'Crosses blood-brain barrier within 30 minutes. Promotes alpha brain waves for calm focus. Pairs well with caffeine for jitter-free alertness, or take at night for sleep.',
    interactions: ['blood pressure medications', 'stimulant medications'],
    category: 'Amino Acid',
  },
  {
    barcode: '693749101017',
    name: 'Vitamin C with Flavonoids',
    brand: 'Thorne',
    dosage: '500mg per capsule',
    ingredients: 'Ascorbic acid, citrus bioflavonoids, hypromellose capsule',
    servingDirections: 'Take 1-3 capsules daily',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'Bioflavonoids enhance vitamin C absorption and action. Split doses throughout the day — your body can only absorb ~500mg at a time. Enhances iron absorption.',
    interactions: ['chemotherapy drugs', 'statins', 'blood thinners'],
    category: 'Vitamin',
  },
  {
    barcode: '024947100114',
    name: 'Selenium',
    brand: 'Pure Encapsulations',
    dosage: '200mcg per capsule',
    ingredients: 'Selenomethionine, hypromellose capsule, ascorbyl palmitate',
    servingDirections: 'Take 1 capsule daily with a meal',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'Selenomethionine is the most bioavailable form. Critical for thyroid function and glutathione production. Do not exceed 400mcg/day total from all sources.',
    interactions: ['blood thinners', 'cholesterol medications', 'niacin'],
    category: 'Mineral',
  },
  {
    barcode: '768990037412',
    name: 'Vitamin D3 + K2',
    brand: 'Nordic Naturals',
    dosage: '1000 IU D3 / 45mcg K2',
    ingredients: 'Vitamin D3 cholecalciferol, Vitamin K2 MK-7, extra virgin olive oil',
    servingDirections: 'Take 1 softgel daily with food',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'D3 and K2 work synergistically — D3 increases calcium absorption, K2 directs it to bones. Take with breakfast containing healthy fats.',
    interactions: ['blood thinners', 'thiazide diuretics', 'steroids'],
    category: 'Vitamin',
  },
  {
    barcode: '850026004410',
    name: 'Lions Mane Mushroom',
    brand: 'Real Mushrooms',
    dosage: '500mg per capsule',
    ingredients: 'Organic lions mane mushroom extract (Hericium erinaceus), hypromellose capsule',
    servingDirections: 'Take 2 capsules daily',
    timeRecommendation: 'morning',
    withFood: true,
    absorptionTips: 'Hot water extracted for maximum beta-glucan content. Take in the morning for cognitive benefits throughout the day. Pairs well with coffee or tea.',
    interactions: ['blood thinners', 'diabetes medications'],
    category: 'Medicinal Mushroom',
  },
  {
    barcode: '733739047182',
    name: 'Melatonin 3mg',
    brand: 'NOW Foods',
    dosage: '3mg per tablet',
    ingredients: 'Melatonin, cellulose, stearic acid, croscarmellose sodium',
    servingDirections: 'Take 1 tablet 30-60 minutes before bedtime',
    timeRecommendation: 'evening',
    withFood: false,
    absorptionTips: 'Start with lowest effective dose. Take 30-60 minutes before bed in a dark room. Sublingual forms absorb faster. Avoid screens after taking.',
    interactions: ['blood thinners', 'immunosuppressants', 'diabetes medications', 'birth control pills'],
    category: 'Hormone',
  },
  {
    barcode: '669076000811',
    name: 'Magnesium L-Threonate',
    brand: 'Jarrow Formulas',
    dosage: '2,000mg (144mg Mg) per serving',
    ingredients: 'Magnesium L-Threonate (Magtein), cellulose, magnesium stearate',
    servingDirections: 'Take 3 capsules daily, 1 in morning, 2 at night',
    timeRecommendation: 'evening',
    withFood: false,
    absorptionTips: 'Only form clinically shown to cross the blood-brain barrier. Excellent for cognitive support and sleep. Split dose — 1 cap AM, 2 caps PM.',
    interactions: ['blood pressure medications', 'antibiotics', 'muscle relaxants'],
    category: 'Mineral',
  },
];

export function lookupByBarcode(barcode: string): ScannedSupplement | null {
  return SUPPLEMENT_DATABASE.find(s => s.barcode === barcode) ?? null;
}

export function lookupRandom(): ScannedSupplement {
  const idx = Math.floor(Math.random() * SUPPLEMENT_DATABASE.length);
  return SUPPLEMENT_DATABASE[idx];
}

export function simulateOCRExtraction(): ScannedSupplement {
  const candidates = SUPPLEMENT_DATABASE.filter(s =>
    ['Vitamin', 'Mineral', 'Amino Acid', 'Adaptogen'].includes(s.category)
  );
  const idx = Math.floor(Math.random() * candidates.length);
  return candidates[idx];
}
